modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="better_mcdonalds_mod"
version="1.3.1"
displayName="Better McDonalds Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://www.curseforge.com/minecraft/mc-mods/better-mcdonalds-mod"
logoFile="logo.png"
authors="simon_mc2008"
description='''
This mod adds many well-known products from McDonald's.
'''

[[dependencies.better_mcdonalds_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




